### ISSUE TITLE
cuda runtime error (7) : too many resources requested for launch

### ISSUE THREAD

**Issue by sdimantsd** [dbolya/yolact#117]
Im not shure if this is yolact problem or pytorch problem...
Im using jetson TX2 and jetson nano (this problem happend in both of them)

$ python3 eval.py --trained_model=weights/yolact_im700_54_800000.pth --score_threshold=0.3 --top_k=10 --image=data/yolact_example_0.png:asd.jpg
Config not specified. Parsed yolact_im700_config from the file name.

Loading model... Done.
THCudaCheck FAIL file=/media/nvidia/WD_BLUE_2.5_1TB/pytorch-v1.1.0/aten/src/THCUNN/generic/SpatialUpSamplingBilinear.cu line=67 error=7 : too many resources requested for launch
Traceback (most recent call last):
  File "eval.py", line 1020, in <module>
    evaluate(net, dataset)
  File "eval.py", line 795, in evaluate
    evalimage(net, inp, out)
  File "eval.py", line 562, in evalimage
    batch = FastBaseTransform()(frame.unsqueeze(0))
  File "/home/ws/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ws/DL/yolact/utils/augmentations.py", line 618, in forward
    img = F.interpolate(img, (cfg.max_size, cfg.max_size), mode='bilinear', align_corners=False)
  File "/home/ws/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 2563, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, _output_size(2), align_corners)
RuntimeError: cuda runtime error (7) : too many resources requested for launch at /media/nvidia/WD_BLUE_2.5_1TB/pytorch-v1.1.0/aten/src/THCUNN/generic/SpatialUpSamplingBilinear.cu:67

can you help me? 
thanks!

**Comment by remindchobits** [comment]
Hello!
I got the same problem, I searched for the solution that modified the CUDA_NUM_THREADS from 1024 to 256.
however, I run it on jetson nano V2, after installing torch=1.1, there's no file named SpatialUpSamplingBilinear.cu in the path THCUNN/generic

Is there any other solution for it, thanks !

**Comment by sdimantsd** [comment]
I saw this solution, but i coldn't found this file, thanks for telling me is not longer exist

**Comment by sdimantsd** [comment]
@remindchobits Can you tell me what what the speed of yolact on jetson TX2?

**Comment by remindchobits** [comment]
@sdimantsd Sorry Dude, I'm not able to run it successfully at present due to this error :(

**Comment by remindchobits** [comment]
now it works, but I got only 1 fps on images with 640*480 resolution

**Comment by remindchobits** [comment]
@sdimantsd The solution is modifying this line:

img = F.interpolate(img, (cfg.max_size, cfg.max_size), mode='bilinear', align_corners=False)

turn the mode='bilinear' into 'nearest', and remove the last parameter 'align_corners'. Besides, there're several interpolate function in the project, you have to modify each of them in order to successfully run the detector

**Comment by dbolya** [comment]
Sounds like this is solved, so I'll close this issue.

**Comment by sdimantsd** [comment]
@remindchobits  sorry for the delay. I change this line. but it's still not working...

**Comment by sdimantsd** [comment]
If anyone is still having this problem, there is a solution that NVIDIA has posted here:
https://forums.developer.nvidia.com/t/pytorch-for-jetson-nano-version-1-5-0-now-available/72048
I think version 1.5 of this pytorch is fixed (cuda10.2 required, has it in JetPack 4.4).
Version 1.4 of pytorch should compile it manually, there are instructions at the end of the link. Note that some changes to the source code need to be made (there is a GIT cluster name that describes the required changes).
I haven't checked myself yet if it works, I'm currently compiling.

**Comment by sdimantsd** [comment]
It turns out there is another problem, DCNv2 code needs to be changed as well.
Files:
src / cuda / dcn_v2_im2col_cuda.cu
src / cuda / dcn_v2_psroi_pooling_cuda.cu
to change
const int CUDA_NUM_THREADS = 1024;
To
const int CUDA_NUM_THREADS = 512;

And compile again

**Comment by AndreiBaraian** [comment]
@remindchobits Did you improve the fps on jetson TX2 or is it only 1 fps?

**Comment by JinLn** [comment]
@sdimantsd Have you solved this problem? And how much FPS is the speed on TX2?
