### ISSUE TITLE
IndexError: List Index out of Range

### ISSUE THREAD

**Issue by Mogarbobac** [dbolya/yolact#249]
Hello, I am running into the following error when trying to run the train.py file.
I do not have a GPU, unsure if this is what is causing the error. If i need to change something could you kindly write down what to change and in what file? I'm really not sure what to do from here. Thank you.

runfile('C:/yolact/train.py', wdir='C:/yolact')
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Initializing weights...
Begin training!

Traceback (most recent call last):

  File "<ipython-input-1-65337cb6595e>", line 1, in <module>
    runfile('C:/yolact/train.py', wdir='C:/yolact')

  File "C:\Miniconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Miniconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/yolact/train.py", line 502, in <module>
    train()

  File "C:/yolact/train.py", line 305, in train
    losses = net(datum)

  File "C:\Miniconda\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)

  File "C:\Miniconda\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])

  File "C:\Miniconda\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)

  File "C:/yolact/train.py", line 143, in forward
    preds = self.net(images)

  File "C:\Miniconda\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)

  File "C:\yolact\yolact.py", line 600, in forward
    outs = self.backbone(x)

  File "C:\Miniconda\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)

  File "C:\yolact\backbone.py", line 292, in forward
    x = layer(x)

  File "C:\Miniconda\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)

  File "C:\Miniconda\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)

  File "C:\Miniconda\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)

  File "C:\yolact\backbone.py", line 233, in forward
    return self.conv2(self.conv1(x)) + x

RuntimeError: CUDA out of memory. Tried to allocate 148.00 MiB (GPU 0; 2.00 GiB total capacity; 1.55 GiB already allocated; 9.63 MiB free; 18.22 MiB cached)

..............................................................................................................................................................................................................

Tried python train.py --config=yolact_base_config --batch_size=1

![image](https://user-images.githubusercontent.com/45700961/70842070-8be95200-1ded-11ea-8472-2c5f24144697.png)

**Comment by sdimantsd** [comment]
I see two problems.
For the first one, try to use smaller batch size. Or maybe your GPU have no enough ram.

**Comment by dbolya** [comment]
Yeah your GPU has way too little RAM (only 2 gbs). I'd suggest using the resnet50 model instead: `yolact_resnet50_config`.

**Comment by abhigoku10** [comment]
@dbolya @Mogarbobac  i generally get cuda out of memory issues in following reasons 
1. when i am training the network with higher resolution images like 2k,4k  in my train set 
2.when there is issues with annotation with the custom dataset , where image id's would have overlapped completely 
3.when i run it on lower gpu systems specifications .
we can solve the 3rd by upgrading the system , is there any validation checks for the 2nd one . 1st it not necessary to since in higher resolution we more defined pixels since at the end the model has to run on 4k resolutions

**Comment by Mogarbobac** [comment]
> Yeah your (pseudo?) GPU has way too little RAM (only 2 gbs). I'd suggest using the resnet50 model instead: `yolact_resnet50_config`.
> 
> But it looks like batch_size=1 is fitting in ram for you at least. I'm not sure what that list index out of range error is about, but perhaps you didn't update your num_classes in config.py properly?
> 
> Actually: I just reread our email chain and you have your classes set as `('yes')`. You want that to be `('yes',)` instead. The former just evaluates to a string (i.e., the list `['y', 'e', 's']`). Perhaps that's your issue?

I tried updating the class name to 'yes', as suggested but no luck. I changed The max size from 550 to 224 to be able to fit my images. Im currently using darknet53 as the database. 

>    2.when there is issues with annotation with the custom dataset , where image id's would have overlapped completely

This may be the issue, but could you further explain "where image id's would have overlapped completely"?

Ill try to get an example of my annotation file

**Comment by Mogarbobac** [comment]
I was able to fix the "List Index out of range error"

Within the config.py

 ----------------------- YOLACT v1.0 CONFIGS ----------------------- 

    yolact_base_config = coco_base_config.copy({
        'name': 'yolact_base',

        # Dataset stuff
        'dataset': my_custom_dataset,
        'num_classes': len(               coco2017_dataset               .class_names) + 1,

        # Image Size
        'max_size': 224,


I changed it to

    yolact_base_config = coco_base_config.copy({
        'name': 'yolact_base',

        # Dataset stuff
        'dataset': my_custom_dataset,
        'num_classes': len(                  my_custom_dataset                 .class_names) + 1,

        # Image Size
        'max_size': 224,


My custom dataset only had 1 class, the coco dataset has like 80. So when it says list index out of range i assume it meant i only had 1 class when i should of had 80. Now that i changed it to my custom dataset i should only have 1 class and the error goes away. 
I post this here so that others may not go through such hardships.
