### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by doit-ceo** [dbolya/yolact#336]
Trying to run eval.py on local machine and getting the following error (RuntimeError: CUDA error: no kernel image is available for execution on the device), Is this related to (CUDA Capability Major/Minor version number:    3.5) ? it should be above 3.7 ? how to solve this ?

----------------------------

python eval.py --trained_model=./yolact/weights/yolact_plus_resnet50_54_800000.pth --config=yolact_plus_resnet50_config --score_threshold=0.15 --top_k=15 --images=test_images:output_images
Loading model...Traceback (most recent call last):
  File "eval.py", line 1097, in <module>
    net = Yolact()
  File "/home/alaa/work/yolcat/yolact/yolact.py", line 402, in __init__
    self.backbone = construct_backbone(cfg.backbone)
  File "/home/alaa/work/yolcat/yolact/backbone.py", line 451, in construct_backbone
    backbone = cfg.type(*cfg.args)
  File "/home/alaa/work/yolcat/yolact/backbone.py", line 77, in __init__
    self.conv1 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3, bias=False)
  File "/home/alaa/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 332, in __init__
    False, _pair(0), groups, bias, padding_mode)
  File "/home/alaa/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 46, in __init__
    self.reset_parameters()
  File "/home/alaa/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 49, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/home/alaa/anaconda3/envs/yolact-env/lib/python3.7/site-packages/torch/nn/init.py", line 315, in kaiming_uniform_
    return tensor.uniform_(-bound, bound)
RuntimeError: CUDA error: no kernel image is available for execution on the device

This is also my cuda query
---------------------

./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GT 710"
  CUDA Driver Version / Runtime Version          10.2 / 10.1
  CUDA Capability Major/Minor version number:    3.5
  Total amount of global memory:                 2001 MBytes (2097938432 bytes)
  ( 1) Multiprocessors, (192) CUDA Cores/MP:     192 CUDA Cores
  GPU Max Clock rate:                            954 MHz (0.95 GHz)
  Memory Clock rate:                             800 Mhz
  Memory Bus Width:                              64-bit
  L2 Cache Size:                                 524288 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            No
  Supports Cooperative Kernel Launch:            No
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 10.2, CUDA Runtime Version = 10.1, NumDevs = 1
Result = PASS

-------------

**Comment by doit-ceo** [comment]
I fixed this by compiling my own pyTorch (it will take 3-4 hours to compile)

export CUDA_HOME=/usr/local/cuda
export USE_CUDA=1

___

this what I did 

___

git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
git submodule sync
git submodule update --init --recursive
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
export CUDA_HOME=/usr/local/cuda
export USE_CUDA=1
conda install pyyaml
python setup.py install

___

Then run the eval (you need to download the yolact_plus_resnet50_54_800000.pth)

___

python eval.py --trained_model=weights/yolact_plus_resnet50_54_800000.pth --config=yolact_plus_resnet50_config --score_threshold=0.15 --top_k=15 --images=test_images:output_images
