### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by EchoAmor** [dbolya/yolact#450]
Thanks for your work!
I want to use yolact++ , when I run the _eval.py_ **on 1 Gpu with python 3.6.9,Pytorch 1.3.1,cuda 10.1**,it always appears this problem:

> error in modulated_deformable_im2col_cuda: invalid device function
> Traceback (most recent call last):
>   File "/home/echo/a_project/yolact/eval.py", line 1104, in <module>
>     evaluate(net, dataset)
>   File "/home/echo/a_project/yolact/eval.py", line 948, in evaluate
>     preds = net(batch)
>   File "/home/echo/anaconda3/envs/YOLACT++/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/echo/a_project/yolact/yolact.py", line 619, in forward
>     p = pred_layer(pred_x)
>   File "/home/echo/anaconda3/envs/YOLACT++/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/echo/a_project/yolact/yolact.py", line 202, in forward
>     priors = self.make_priors(conv_h, conv_w, x.device)
>   File "/home/echo/a_project/yolact/yolact.py", line 247, in make_priors
>     self.priors = torch.Tensor(prior_data, device=device).view(-1, 4).detach() 
> **RuntimeError: CUDA error: an illegal memory access was encountered**

![Screenshot from 2020-05-19 16-47-18](https://user-images.githubusercontent.com/25685837/82305598-6d1c6680-99f0-11ea-8929-484056c0e501.png)

Do u know how to fix this? I have googled for a  while but still don't know why the problem appears and how to solve it. I will very appreciate it if u can reply me !

**Comment by EchoAmor** [comment]
I have fixed this by reinstalling pytorch==1.0.1 and cuda ==10.0, this bug appears maybe because I used 1.3.0 before, just the version problem.
