### ISSUE TITLE
RuntimeError: CUDA out of memory while calculating mAP

### ISSUE THREAD

**Issue by suchiz** [dbolya/yolact#527]
I have a weird error. I have a 1080 GTX 8Go RAM and I can fill this with 5 images at the same time and it works perfectly !
But when I change the batch_size to 1 or 2. It trains well but when it comes to calculate mAP, it crashes running out of memory ... Somehow ...? I don't understand why it is working with batch 5 but not lower ?

[  1]     900 || B: 4.245 | C: 3.799 | M: 5.265 | S: 0.380 | I: 1.625 | T: 15.314 || ETA: 5 days, 19:05:31 || timer: 0.415
[  1]     910 || B: 4.232 | C: 3.763 | M: 5.271 | S: 0.376 | I: 1.473 | T: 15.115 || ETA: 5 days, 18:56:14 || timer: 0.431

Computing validation mAP (this may take a while)...

Traceback (most recent call last):
  File "train.py", line 506, in <module>
    train()
  File "train.py", line 371, in train
    compute_validation_map(epoch, iteration, yolact_net, val_dataset, log if args.log else None)
  File "train.py", line 494, in compute_validation_map
    val_info = eval_script.evaluate(yolact_net, dataset, train_mode=True)
  File "C:\Users\EspaceInno01\Documents\Yolact++\yolact-master\eval.py", line 960, in evaluate
    prep_metrics(ap_data, preds, img, gt, gt_masks, h, w, num_crowd, dataset.ids[image_idx], detections)
  File "C:\Users\EspaceInno01\Documents\Yolact++\yolact-master\eval.py", line 404, in prep_metrics
    classes, scores, boxes, masks = postprocess(dets, w, h, crop_masks=args.crop, score_threshold=args.score_threshold)
  File "C:\Users\EspaceInno01\Documents\Yolact++\yolact-master\layers\output_utils.py", line 91, in postprocess
    masks = F.interpolate(masks.unsqueeze(0), (h, w), mode=interpolation_mode, align_corners=False).squeeze(0)
  File "C:\Users\EspaceInno01\Anaconda3\envs\servertorch\lib\site-packages\torch\nn\functional.py", line 2530, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, _output_size(2), align_corners)
RuntimeError: CUDA out of memory. Tried to allocate 5.93 GiB (GPU 0; 8.00 GiB total capacity; 689.46 MiB already allocated; 5.30 GiB free; 962.00 MiB reserved in total by PyTorch)

I tried to flush cuda with torch.cuda.empty_cache() right before loading another image (get_item) but same issue ... Any ideas ?

UPDATE: batch_size=5 is the only one working... I cant calculate mAP on the others, but I can still use them to predict ...

**Comment by jing5j** [comment]
Hi, did you find the reason? I met the same problem..

**Comment by suchiz** [comment]
Hi there,

I do not really remember. It has been a long time i didn't work on it. I fixed it for sure. As long as I remember there was a problem in eval.py at evalimage function.

    frame = torch.from_numpy(cv2.imread(path)).cuda().float()
    batch = FastBaseTransform()(frame.unsqueeze(0))
    preds = net(batch)

unfortunaly I do not remember what I've done exactly... but I hope this will lead you to your solution !

**Comment by jing5j** [comment]
> Hi there,
> 
> I do not really remember. It has been a long time i didn't work on it. I fixed it for sure. As long as I remember there was a problem in eval.py at evalimage function.
> 
> ```
> frame = torch.from_numpy(cv2.imread(path)).cuda().float()
> batch = FastBaseTransform()(frame.unsqueeze(0))
> preds = net(batch)
> ```
> 
> unfortunaly I do not remember what I've done exactly... but I hope this will lead you to your solution !

I did some search on internet, which suggested to add "with torch.no_grad()" before preds = net(batch), I have tried that but it doesn't work.

**Comment by suchiz** [comment]
hi there,

Oh yeah i remember now, with that torch no_grad. It should be done even before. I put it in the __main__ of eval.py

if __name__ == '__main__':
    parse_args()

    if args.config is not None:
        set_cfg(args.config)

    if args.trained_model == 'interrupt':
        args.trained_model = SavePath.get_interrupt('weights/')
    elif args.trained_model == 'latest':
        args.trained_model = SavePath.get_latest('weights/', cfg.name)

    if args.config is None:
        model_path = SavePath.from_str(args.trained_model)
        # TODO: Bad practice? Probably want to do a name lookup instead.
        args.config = model_path.model_name + '_config'
        print('Config not specified. Parsed %s from the file name.\n' % args.config)
        set_cfg(args.config)

    if args.detect:
        cfg.eval_mask_branch = False

    if args.dataset is not None:
        set_dataset(args.dataset)

    with torch.no_grad():
        if not os.path.exists('results'):
            os.makedirs('results')

        if args.cuda:
            cudnn.fastest = True
            torch.set_default_tensor_type('torch.cuda.FloatTensor')
        else:
            torch.set_default_tensor_type('torch.FloatTensor')

        if args.resume and not args.display:
            with open(args.ap_data_file, 'rb') as f:
                ap_data = pickle.load(f)
            calc_map(ap_data)
            exit()

        if args.image is None and args.video is None and args.images is None:
            dataset = COCODetection(cfg.dataset.valid_images, cfg.dataset.valid_info,
                                    transform=BaseTransform(), has_gt=cfg.dataset.has_gt)
            prep_coco_cats()
        else:
            dataset = None        

        print('Loading model...', end='')
        net = Yolact()
        net.load_weights(args.trained_model)
        net.eval()
        print(' Done.')

        if args.cuda:
            net = net.cuda()

        evaluate(net, dataset)

like this
